### ISSUE TITLE
Error while executing example scripts

### ISSUE THREAD

**Issue by tarak77** [michaelhabeck/isdhic#1]
Hi! I am trying to run the examples from scripts/ folder. To do so I first executed run_hmc.py and when I am running analyze.py, I get the following error:

Traceback (most recent call last):
  File "analyze.py", line 52, in <module>
    X = np.array([state.positions for state in samples]).reshape(len(samples),-1,3)
NameError: name 'samples' is not defined

Any help will be appreciated!

**Comment by XuanHeIIIS** [comment]
Hi! This situation also comes to me, could you please tell me how you fixed it?

**Comment by XuanHeIIIS** [comment]
Ok, I just fixed it!
